export const __DEV__ = !['production', 'prod'].includes(process.env.NODE_ENV || 'local');
export const CONSTANTS = Object.freeze({
    symbols: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz",
    digits: "0123456789",
    authHeader: 'AuthToken',
    joinCodeLen: 6,
    startingCoinBalance: 30,
    otpLen: 4,
    cache: 'redis://localhost',
    db: {
        connectionLimit : 30,
        host            : __DEV__ ? 'localhost' : process.env.DB_HOST,
        user            : __DEV__ ? 'root' : process.env.DB_USER,
        password        : __DEV__ ? 'password' : process.env.DB_PASSWORD,
        database        : __DEV__ ? 'rainbow-catalog' : process.env.DB_NAME
    },
    tables: {
        farm: 'farm',
        farmer: 'farmer',
        farmInventory: 'farmInventory',
        farmInventoryLedger: 'farmInventoryLedger',
        farmPrefs: 'farmPrefs',
        productCatalog: 'productCatalog',
        ondcSubscriberInfo: 'ondcSubscriberInfo',
        order: 'buyerOrder',
        orderPayment: 'orderPayment',
        rating: 'rating',
    },
    response: {
        ok: { message: 'ok' },
    },
    ondcRequestRedisList: 'ondcRequestList',
    ondcRequestRedisChannel: 'ondcRequestChannel',
    testChannel: 'testChannel',
    deliveryPromiseInDays: 7,
    name: "DhoomNow",
    gps: "12.9349377,77.6055586",
    contact: '+917978608446',
    email: 'support@subnub.com',
    apiHost: __DEV__ ? 'http://localhost:3000' : 'https://ondc.dhoomnow.com',
    trackingUrl: '/tracking?orderId=%s',
});
