export const __DEV__ = !['production', 'prod'].includes(process.env.NODE_ENV || 'local');
export const CONSTANTS = Object.freeze({
    symbols: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz",
    digits: "0123456789",
    authHeader: 'AuthToken',
    joinCodeLen: 6,
    startingCoinBalance: 30,
    otpLen: 4,
    otpExpiresInSeconds: 300,
    cache: process.env.CACHE_URL,
    db: {
        connectionLimit : 30,
        host            : process.env.DB_HOST,
        user            : process.env.DB_USER,
        password        : process.env.DB_PASSWORD,
        database        : process.env.DB_NAME
    },
    tables: {
        farm: 'farm',
        farmer: 'farmer',
        farmInventory: 'farmInventory',
        farmInventoryLedger: 'farmInventoryLedger',
        farmPrefs: 'farmPrefs',
        productCatalog: 'productCatalog',
        ondcSubscriberInfo: 'ondcSubscriberInfo',
        buyerOrder: 'buyerOrder',
        sellerOrder: 'sellerOrder',
        orderPayment: 'orderPayment',
        rating: 'rating',
        ondcContext: 'ondcContext',
    },
    response: {
        ok: { message: 'ok' },
    },
    ondcRequestRedisList: 'ondcRequestList',
    ondcRequestRedisChannel: 'ondcRequestChannel',
    testChannel: 'testChannel',
    deliveryPromiseInDays: 7,
    name: "DhoomNow",
    gps: "12.9349377,77.6055586",
    contact: '+917978608446',
    email: 'support@subnub.com',
    apiHost: process.env.API_HOST,
    trackingUrl: '/tracking?orderId=%s',
    buyerFinderFee: 0.02,
    bgTaskRedisList: 'bgTaskList',
    bgTaskRedisChannel: 'bgTaskChannel',
});
